spring.application.name=organoindia


# Datasource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=CLEANIE
spring.datasource.password=cleaniepass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hikari CP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Do not execute DDL automatically on application startup
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

# Customize the base path for all SDR repositories
spring.data.rest.basePath=/api